// Copyright 2026 Mahmoud Harmouch.
//
// Licensed under the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

//! Unit tests for the image metadata watermark strippers.

use cum_rs::image_meta::{clean_image, detect_image_format, inspect_image};
use cum_rs::types::ImageFormat;

/// Minimal valid PNG with a 1×1 white pixel (IHDR + IDAT + IEND, no metadata).
fn minimal_png() -> Vec<u8> {
    vec![
        0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG magic
        // IHDR chunk (length=13)
        0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // "IHDR"
        0x00, 0x00, 0x00, 0x01, // width=1
        0x00, 0x00, 0x00, 0x01, // height=1
        0x08, 0x02, 0x00, 0x00, 0x00, // 8-bit RGB
        0x90, 0x77, 0x53, 0xDE, // CRC
        // IDAT chunk (length=12, minimal deflate for 1×1 white)
        0x00, 0x00, 0x00, 0x0C, 0x49, 0x44, 0x41, 0x54, // "IDAT"
        0x08, 0xD7, 0x63, 0xF8, 0xFF, 0xFF, 0x3F, 0x00, 0x05, 0xFE, 0x02, 0xFE, 0xDC, 0xCC, 0x59,
        0xE7, // CRC
        // IEND chunk (length=0)
        0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, // "IEND"
        0xAE, 0x42, 0x60, 0x82, // CRC
    ]
}

/// Builds a PNG with a synthetic iTXt metadata chunk.
fn png_with_itxt_chunk() -> Vec<u8> {
    let base = minimal_png();
    let keyword = b"Comment\0";
    let text = b"Generated by Claude AI provider";
    let mut data: Vec<u8> = Vec::new();
    data.extend_from_slice(keyword);
    data.extend_from_slice(b"\0\0\0\0");
    data.extend_from_slice(text);
    let length = (data.len() as u32).to_be_bytes();

    let chunk_type = b"iTXt";
    let crc_input: Vec<u8> = [chunk_type, data.as_slice()].concat();
    let crc = calculate_crc32(&crc_input);

    let mut result = base[..base.len() - 12].to_vec();
    result.extend_from_slice(&length);
    result.extend_from_slice(chunk_type);
    result.extend_from_slice(&data);
    result.extend_from_slice(&crc.to_be_bytes());
    result.extend_from_slice(&base[base.len() - 12..]);
    result
}

/// Builds a PNG with a synthetic C2PA chunk.
fn png_with_c2pa_chunk() -> Vec<u8> {
    let base = minimal_png();
    let data = b"fake-c2pa-manifest-data";
    let length = (data.len() as u32).to_be_bytes();
    let chunk_type = b"C2PA";
    let crc_input: Vec<u8> = [chunk_type, data.as_slice()].concat();
    let crc = calculate_crc32(&crc_input);

    let mut result = base[..base.len() - 12].to_vec();
    result.extend_from_slice(&length);
    result.extend_from_slice(chunk_type);
    result.extend_from_slice(data);
    result.extend_from_slice(&crc.to_be_bytes());
    result.extend_from_slice(&base[base.len() - 12..]);
    result
}

/// Minimal CRC-32 implementation for building test PNG chunks.
fn calculate_crc32(data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFF_FFFF;
    for &byte in data {
        crc ^= byte as u32;
        for _ in 0..8 {
            if crc & 1 != 0 {
                crc = (crc >> 1) ^ 0xEDB8_8320;
            } else {
                crc >>= 1;
            }
        }
    }
    !crc
}

/// Minimal valid JPEG (2×2 pixels, no EXIF).
fn minimal_jpeg() -> Vec<u8> {
    vec![
        0xFF, 0xD8, 0xFF, 0xE0, // SOI + APP0 marker
        0x00, 0x10, // APP0 length = 16 bytes
        0x4A, 0x46, 0x49, 0x46, 0x00, // "JFIF\0"
        0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, // JFIF header
        0xFF, 0xD9, // EOI
    ]
}

/// Builds a JPEG with a synthetic APP1 (EXIF) segment.
fn jpeg_with_exif() -> Vec<u8> {
    let mut jpeg = vec![0xFF, 0xD8]; // SOI
    let exif_payload = b"Exif\0\0fake-exif-data-here";
    let seg_len = (exif_payload.len() as u16 + 2).to_be_bytes();
    jpeg.push(0xFF);
    jpeg.push(0xE1); // APP1
    jpeg.extend_from_slice(&seg_len);
    jpeg.extend_from_slice(exif_payload);
    jpeg.extend_from_slice(&[0xFF, 0xD9]); // EOI
    jpeg
}

/// Builds a JPEG with a synthetic APP11 (JUMBF / C2PA) segment.
fn jpeg_with_c2pa() -> Vec<u8> {
    let mut jpeg = vec![0xFF, 0xD8]; // SOI
    let c2pa_payload = b"fake-c2pa-jumbf-manifest-data";
    let seg_len = (c2pa_payload.len() as u16 + 2).to_be_bytes();
    jpeg.push(0xFF);
    jpeg.push(0xEB); // APP11
    jpeg.extend_from_slice(&seg_len);
    jpeg.extend_from_slice(c2pa_payload);
    jpeg.extend_from_slice(&[0xFF, 0xD9]); // EOI
    jpeg
}

/// Minimal WebP RIFF file.
fn minimal_webp() -> Vec<u8> {
    let vp8l = b"VP8L";
    let vp8_data = b"\x2f\x00\x00\x00\x00"; // minimal VP8L
    let vp8_len = (vp8l.len() as u32 + 4 + vp8_data.len() as u32).to_le_bytes();
    let webp_id = b"WEBP";
    let inner: Vec<u8> = [vp8l.as_slice(), &vp8_len[..4], vp8_data].concat();
    let riff_len = (webp_id.len() as u32 + inner.len() as u32).to_le_bytes();
    let mut out = vec![b'R', b'I', b'F', b'F'];
    out.extend_from_slice(&riff_len);
    out.extend_from_slice(webp_id);
    out.extend_from_slice(&inner);
    out
}

#[test]
fn test_detect_png() {
    let png = minimal_png();
    assert_eq!(detect_image_format(&png), Some(ImageFormat::Png));
}

#[test]
fn test_detect_jpeg() {
    let jpeg = minimal_jpeg();
    assert_eq!(detect_image_format(&jpeg), Some(ImageFormat::Jpeg));
}

#[test]
fn test_detect_webp() {
    let webp = minimal_webp();
    assert_eq!(detect_image_format(&webp), Some(ImageFormat::Webp));
}

#[test]
fn test_detect_svg() {
    let svg = b"<svg xmlns=\"http://www.w3.org/2000/svg\"/>";
    assert_eq!(detect_image_format(svg), Some(ImageFormat::Svg));
}

#[test]
fn test_detect_unknown_returns_none() {
    let garbage = b"not-an-image-at-all";
    assert_eq!(detect_image_format(garbage), None);
}

#[test]
fn test_inspect_png_with_itxt_finds_chunk() {
    let png = png_with_itxt_chunk();
    let report = inspect_image(&png).unwrap();
    assert_eq!(report.format, ImageFormat::Png);
    assert!(!report.findings.is_empty(), "should find iTXt chunk");
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.description.contains("iTXt"))
    );
}

#[test]
fn test_inspect_png_with_c2pa_finds_chunk() {
    let png = png_with_c2pa_chunk();
    let report = inspect_image(&png).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.description.contains("C2PA"))
    );
}

#[test]
fn test_inspect_minimal_png_no_findings() {
    let png = minimal_png();
    let report = inspect_image(&png).unwrap();
    assert!(
        report.findings.is_empty(),
        "minimal PNG should have no findings"
    );
}

#[test]
fn test_clean_png_strips_itxt() {
    let dirty = png_with_itxt_chunk();
    let clean = clean_image(&dirty).unwrap();
    assert!(clean.len() < dirty.len(), "cleaned PNG should be smaller");
    assert!(
        clean.windows(4).all(|w| w != b"iTXt"),
        "iTXt chunk should be absent from cleaned PNG"
    );
}

#[test]
fn test_clean_png_strips_c2pa() {
    let dirty = png_with_c2pa_chunk();
    let clean = clean_image(&dirty).unwrap();
    assert!(
        clean.windows(4).all(|w| w != b"C2PA"),
        "C2PA chunk should be absent from cleaned PNG"
    );
}

#[test]
fn test_clean_png_preserves_magic() {
    let dirty = png_with_itxt_chunk();
    let clean = clean_image(&dirty).unwrap();
    assert!(
        clean.starts_with(b"\x89PNG\r\n\x1a\n"),
        "PNG magic must be preserved"
    );
}

#[test]
fn test_clean_png_no_metadata_unchanged_structure() {
    let png = minimal_png();
    let clean = clean_image(&png).unwrap();
    assert_eq!(
        clean.len(),
        png.len(),
        "clean PNG without metadata should be unchanged"
    );
}

#[test]
fn test_inspect_jpeg_with_exif_finds_app1() {
    let jpeg = jpeg_with_exif();
    let report = inspect_image(&jpeg).unwrap();
    assert!(!report.findings.is_empty());
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.description.contains("APP1"))
    );
}

#[test]
fn test_inspect_jpeg_with_c2pa_finds_app11() {
    let jpeg = jpeg_with_c2pa();
    let report = inspect_image(&jpeg).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.description.contains("APP11"))
    );
}

#[test]
fn test_clean_jpeg_strips_exif() {
    let dirty = jpeg_with_exif();
    let clean = clean_image(&dirty).unwrap();
    assert!(
        clean.starts_with(&[0xFF, 0xD8]),
        "JPEG SOI must be preserved"
    );
    assert!(clean.len() <= dirty.len());
}

#[test]
fn test_clean_jpeg_strips_c2pa_app11() {
    let dirty = jpeg_with_c2pa();
    let clean = clean_image(&dirty).unwrap();
    assert!(
        !clean.windows(2).any(|w| w == [0xFF, 0xEB]),
        "APP11 marker should be absent from cleaned JPEG"
    );
}

#[test]
fn test_clean_jpeg_preserves_eoi() {
    let dirty = jpeg_with_exif();
    let clean = clean_image(&dirty).unwrap();
    assert!(clean.ends_with(&[0xFF, 0xD9]), "JPEG EOI must be preserved");
}

#[test]
fn test_inspect_svg_with_metadata() {
    let svg = br#"<svg xmlns="http://www.w3.org/2000/svg"><metadata>AI generated</metadata></svg>"#;
    let report = inspect_image(svg).unwrap();
    assert_eq!(report.format, ImageFormat::Svg);
    assert!(!report.findings.is_empty());
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.description.contains("metadata"))
    );
}

#[test]
fn test_clean_svg_removes_metadata_block() {
    let svg = b"<svg><metadata>AI generated by Claude</metadata><circle/></svg>";
    let clean = clean_image(svg).unwrap();
    let clean_str = std::str::from_utf8(&clean).unwrap();
    assert!(!clean_str.contains("<metadata>"));
    assert!(
        clean_str.contains("<circle/>"),
        "SVG content should be preserved"
    );
}

#[test]
fn test_clean_svg_removes_data_ai_attr() {
    let svg = b"<svg><rect data-ai-provider=\"claude\" /></svg>";
    let clean = clean_image(svg).unwrap();
    let clean_str = std::str::from_utf8(&clean).unwrap();
    assert!(!clean_str.contains("data-ai-provider"));
}

#[test]
fn test_inspect_image_unsupported_format_errors() {
    let result = inspect_image(b"not-an-image");
    assert!(result.is_err());
}

#[test]
fn test_clean_image_unsupported_format_errors() {
    let result = clean_image(b"not-an-image");
    assert!(result.is_err());
}
