name: 🧹 Cargo Clippy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: 🔍 Clippy
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🦀 Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: 🧪 Run Clippy
        run: cargo clippy --tests --all-features -- -D warnings
