name: 📚 Docs

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: 📚 Build rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build docs
        run: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: target/doc
